;;      DEVICE TABLE ENTRYS.

        ORG     0

DEV.NAM DS      2               ; DEVICE NAME
DEV.RES DS      1               ; DRIVER RESIDENT CODE
DR.IM   EQU     00000001B       ; DRIVER IN MEMORY
DR.PRG  EQU     00000010B       ; DRIVER PERMANENTLY RESIDENT

DEV.JMP DS      1               ; JMP TO PROCESSOR
DEV.DDA DS      2               ; DRIVER ADDRESS
DEV.FLG DS      1               ; FLAG BYTE
DT.DD   EQU     00000001B       ; DIRECTORY DEVICE
DT.CR   EQU     00000010B       ; CAPABLE OF READ OPERATION
DT.CW   EQU     00000100B       ; CAPABLE OF WRITE OPERATION

DEV.GRT DS      2               ; ADDRESS OF GROUP RESERVATION TABLE (IF DIRECTORY)
DEV.SPG DS      1               ; SECTORS PER GROUP THIS DEVICE
DEV.MUM                         ; MOUNTED UNIT MASK
DEV.MNU DS      1               ; MAXIMUM NUMBER OF UNITS
DEV.DVL DS      2               ; DRIVER BYTE LENGTH
DEV.DVG DS      1               ; DRIVER ROUTINE GROUP ADDRESS
DEV.DIR DS      2               ; DIRECTORY FIRST SECTOR ADDRESS
DEV.GTS DS      2               ; GET SECTOR NUMBER
