;;      S.INT - SYSTEM INTERNAL WORKAREA DEFINITIONS.
;
;       THESE CELLS ARE REFERENCED BY OVERLAYSAND MAIN CODE, AND
;       MUST THEREFORE RESIDE IN FIXED LOW MEMORY


        ORG     S.INT

;;      CONSOLE STATUS FLAGS

S.CDB   DS      1               ; CONSOLE DESCRIPTOR BYTE
CDB.H85 EQU     00000000B
CDB.H84 EQU     00000001B       ; =0 IF H8-5, =1 IF H8-4
S.BAUD  DS      2               ; [0-14]  H8-4 BAUD RATE, =0 IF H8-5
;                               ; [15]    =1 IF BAUD RATE => 2 STOP BITS
;

;;      TABLE ADDRESS WORDS

S.DLINK DS      2               ; ADDRESS OF DATA IN HDOS CODE
