;;      S.VAL - SYSTEM VALUE DEFINITIONS.
;
;       THESE VALUES ARE SET AND MAINTAINED BY THE SYSTEM.
;
;       THE DECK HOSQEU MUST BE MODIFIED WHEN THIS IS MODIFIED.

        ORG     S.VAL

S.DATE  DS      9               ; SYSTEM DATE (IN ASCII)
S.DATC  DS      2               ; CODED DATE
S.TIME  DS      4               ; TIME FROM MIDNIGHT (IN TICS)
S.HIMEM DS      2               ; HARDWARE HIGH MEMORY ADDRESS+1

S.SYSM  DS      2               ; FWA RESIDENT SYSTEM

S.USRM  DS      2               ; LWA USER MEMORY

S.OMAX  DS      2               ; MAX OVERLAY SIZE FOR SYSTEM

;;      THE FOLLOWING FIVE CELLS SHOULD BE MODIFIED/READ ONLY VIA THE .CONSL SYSCALL

CSL.ECH EQU     10000000B       ; SUPPRESS ECHO
CSL.WRP EQU     00000010B       ; WRAP LINES AT WIDTH
CSL.CHR EQU     00000001B       ; OPERATE IN CHARACTER MODE

I.CSLMD EQU     0               ; S.CSLMD IS FIRST BYTE
S.CSLMD EQU     1               ; CONSOLE MODE

CTP.BKS EQU     10000000B       ; TERMINAL PROCESSES BACKSPACES
CTP.MLI EQU     00100000B       ; MAP LOWER CASE TO UPPER ON INPUT
CTP.MLO EQU     00010000B       ; MAP LOWER CASE TO UPPER ON OUTPUT
CTP.2SB EQU     00001000B       ; TERMINAL NEEDS TWO STOP BITS
CTP.BKM EQU     00000010B       ; MAP BKSP (UPON INPUT) TO RUBOUT
CTP.TAB EQU     00000001B       ; TERMINAL SUPPORTS TAB CHARACTERS

I.CONTY EQU     1               ; S.CONTY IS 2ND BYTE
S.CONTY DS      1               ; CONSOLE TYPE FLAGS
I.CUSOR EQU     2               ; S.CUSOR IS 3RD BYTE
S.CUSOR DS      1               ; CURRENT CURSOR POSITION
I.CONWI EQU     3               ; S.CONWI IS 4TH BYTE
S.CONWI DS      1               ; CONSOLE WIDTH

CO.FLG  EQU     00000001B       ; CTL-O FLAG
CS.FLG  EQU     10000000B       ; CTL-S FLAG

I.CONFL EQU     4               ; S.CONFL IS 5TH BYTE
S.CONFL DS      1               ; CONSOLE FLAGS

S.CAADR DS      2               ; ADDRESS FOR ABORT PROCESSING (>256 IF VALID)
S.CCTAB DS      6               ; ADDR FOR CTL-A, CTL-B, CTL-C PROCESSING
