;;      S.VAL - SYSTEM VALUTE DEFINTIONS.
;
;       THESE VALUES ARE SET AND MAINTAINED BY THE SYSTEM.
;
;       THE DECK HOSQEU MUST BE MODIFIED WHEN THIS IS MODIFIED.

        ORG     S.VAL

S.DATE  DS      9               ; SYSTEM DATE (IN ASCII)
S.DATC  DS      2               ; CODED DATE
S.TIME  DS      4               ; TIME FROM MIDNIGHT (IN TICS)
S.HIMEM DS      2               ; HARDWARE HIGH MEMORY ADDRESS+1

S.SYSM  DS      2               ; FWA RESIDENT SYSTEM

S.USRM  DS      2               ; LWA USER MEMORY

S.OMAX  DS      2               ; MAX OVERLAY SIZE FOR SYSTEM

;;      THE FOLLOWING FIVE CELLS SHOULD BE MODIFIED/READ ONLY VIA THE .CONSL SYSCALL

CSL.ECH EQU     10000000B       ; SUPPRESS ECHO
CSL.WRP EQU     00000010B       ; WRAP LINES AT WIDTH
CSL.CHR EQU     00000001B       ; OPERATE IN CHARACTER MODE

I.CSLMD EQU     0               ; S.CSLMD IS FIRST BYTE
S.CSLMD EQU     1               ; CONSOLE MODE

CTP.BKS EQU     10000000B       ; TERMINAL PROCESSES BACKSPACES
