; MTR - SOURCE CODE FOR THIS WAS NOT PUBLISHED BY THE HEATH CO. AND
; HAS BEEN REVERSE ENGINEERED.

MFLAG   EQU     20010Q          ; USER FLAG OPTIONS
TICCNT  EQU     20033Q          ; CLOCK TICK COUNTER
UIVEC   EQU     20037Q          ; USER INTERRUPT VECTOR
