; DEFINES FOR 8250 UART/ACE CHIP
;
; REVERSE ENGINEERED AS ORIGINAL SOURCE CODE WAS NOT PUBLISHED.

SC.ACE  EQU     350Q            ; I/O PORT FOR ACE

UC.8BW  EQU     3
UC.DLA  EQU     200Q
UC.DR   EQU     1
UC.THE  EQU     40Q
UR.DLL  EQU     0
UR.IER  EQU     1
UR.LCR  EQU     3
UR.LSR  EQU     4
UR.RBR  EQU     0
UR.THR  EQU     0
UR.DLM  EQU     1
