; Macros to emulate the Heathkit HDOS assembler.

ERRPL   MACRO EXP
        IF (EXP) > 0
          ERROR Expression is positive
        ENDIF
        ENDM

ERRMI   MACRO EXP
        IF (EXP) < 0
          ERROR Expression is negative
        ENDIF
        ENDM

ERRNZ   MACRO EXP
        IF (EXP) != 0
          ERROR Expression is not zero
        ENDIF
        ENDM

ERRZR   MACRO EXP
        IF (EXP) == 0
          ERROR Expression is zero
        ENDIF
        ENDM
