;; MISCELLANEOUS EQUATES FROM H17 BOOT ROM.
;  REFER TO H17 BOOT ROM IF MORE INFORMATION REQUIRED

WHD     EQU     17235Q          ; WAIT FOR HOLE ROUTINE ENTRY POINT
WNH     EQU     17271Q          ; WAIT FOR NO HOLE ROUTINE ENTRY POINT

BOOTAL  EQU     130Q            ; NUMBER OF RAM TO CLEAR
BOOTA   EQU     17532Q          ; RAM CLEAR START LOCATION
DMOVE   EQU     14252Q          ; MOVE DATA ROUTINE
D.RAML  EQU     37Q
DZERO   EQU     14612Q          ; ZERO RAM ROUTINE
AIO.UNI EQU     20461Q          ; DISK UNIT NUMBER STORAGE
UIVEC   EQU     20037Q          ; USER INTERRUPT VECTOR
CLOCK17 EQU     16031Q          ; Z17 TIMER INTERRUPT HANDLER LOCATION
R.ABORT EQU     15766Q          ; RESET Z17 ROUTINE LOCATION
R.READ  EQU     16077Q          ; READ Z17 ROUTINE LOCATION
D.SDP   EQU     20206Q          ; SET DEVICE PARAMETER RAM LOCATION
SDP3    EQU     17073Q          ; SET DEVICE PARAMETER ENTRY
EIXIT   EQU     16027Q          ; EI/RET LOCATION
ERPTCNT EQU     12Q             ; ERROR COUNT
D.OECNT EQU     20264Q
