;       HDOS SYSTEM EQUIVALENCES.
;

S.GRT   EQU     12000Q          ; SYSTEM AREA FOR GRT0
S.GRT1  EQU     12400Q          ; SYSTEM AREA FOR GRT 1
SECSCR  EQU     13000Q          ; SYSTEM 512 BYTE SCRATCH AREA
ROMBOOT EQU     14000Q          ; ROM BOOT ENTRY
