;; MISCELLANEOUS EQUATES FROM H17 BOOT ROM.
;  REFER TO H17 BOOT ROM IF MORE INFORMATION REQUIRED

WHD     EQU     36235Q          ; WAIT FOR HOLE ROUTINE ENTRY POINT
WNH     EQU     36271Q          ; WAIT FOR NO HOLE ROUTONE ENTRY POINT

BOOTAL  EQU     130Q            ; NUMBER OF RAM TO CLEAR
BOOTA   EQU     37132Q          ; RAM CLEAR START LOCATION
DMOVE   EQU     30252Q          ; MOVE DATA ROUTINE
D.RAML  EQU     37Q
DZERO   EQU     31212Q          ; ZERO RAM ROUTINE
AIO.UNI EQU     41061Q          ; DISK UNIT NUMBER STORAGE
UIVEC   EQU     40037Q          ; USER INTERRUPT VECTOR
CLOCK17 EQU     34031Q          ; Z17 TIMER INTERRUPT HANDLER LOCATION
R.ABORT EQU     33366Q          ; RESET Z17 ROUTINE LOCATION
R.READ  EQU     34077Q          ; READ Z17 ROUTINE LOCATION
D.SDP   EQU     40206Q          ; SET DEVICE PARAMETER RAM LOCATION
SDP3    EQU     36073Q          ; SET DEVICE PARAMETER ENTRY
EIXIT   EQU     34027Q          ; EI/RET LOCATION
ERPTCNT EQU     12Q             ; ERROR COUNT
D.OECNT EQU     40264Q
